app = "wpa-surpresso"
primary_region = "fra"

[env]
PORT = "8080"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8080
min_machines_running = 0
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"

[deploy]
release_command = "npm --prefix backend run prisma:migrate"
