import { hashPassword } from '../../domain/security/passwordHasher.js';

const now = new Date().toISOString();

export const seed = {
  users: [
    {
      id: 'user-owner-1',
      email: 'owner@surpresso.local',
      phone: '+380730000001',
      passwordHash: hashPassword('Owner123!'),
      fullName: 'Owner Demo',
      role: 'owner',
      positionTitle: 'Собственник',
      isActive: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'user-director-1',
      email: 'director@surpresso.local',
      phone: '+380730000002',
      passwordHash: hashPassword('Director123!'),
      fullName: 'Director Demo',
      role: 'director',
      positionTitle: 'Директор',
      isActive: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'user-service-head-1',
      email: 'service.head@surpresso.local',
      phone: '+380730000003',
      passwordHash: hashPassword('ServiceHead123!'),
      fullName: 'Service Head Demo',
      role: 'service_head',
      positionTitle: 'Руководитель сервиса',
      isActive: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'user-manager-1',
      email: 'manager@surpresso.local',
      phone: '+380730000006',
      passwordHash: hashPassword('Manager123!'),
      fullName: 'Operations Manager Demo',
      role: 'manager',
      positionTitle: 'Менеджер сервиса',
      isActive: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'user-service-engineer-field-1',
      email: 'field.engineer@surpresso.local',
      phone: '+380730000010',
      passwordHash: hashPassword('FieldEngineer123!'),
      fullName: 'Field Engineer Demo',
      role: 'service_engineer',
      positionTitle: 'Выездной мастер',
      workMode: 'field',
      capacity: 7,
      maxCritical: 2,
      canTakeUrgent: true,
      canTakeFieldRequests: true,
      isActive: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'user-service-engineer-auto-1',
      email: 'auto.engineer@surpresso.local',
      phone: '+380730000011',
      passwordHash: hashPassword('AutoEngineer123!'),
      fullName: 'Auto Coffee Engineer Demo',
      role: 'service_engineer',
      positionTitle: 'Мастер по автоматам',
      workMode: 'inhouse',
      capacity: 6,
      maxCritical: 2,
      canTakeUrgent: true,
      canTakeFieldRequests: false,
      isActive: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'user-service-engineer-universal-1',
      email: 'universal.engineer@surpresso.local',
      phone: '+380730000012',
      passwordHash: hashPassword('UniversalEngineer123!'),
      fullName: 'Universal Engineer Demo',
      role: 'service_engineer',
      positionTitle: 'Универсальный мастер',
      workMode: 'hybrid',
      capacity: 8,
      maxCritical: 3,
      canTakeUrgent: true,
      canTakeFieldRequests: true,
      isActive: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'user-sales-manager-1',
      email: 'sales@surpresso.local',
      phone: '+380730000005',
      passwordHash: hashPassword('Sales123!'),
      fullName: 'Sales Manager Demo',
      role: 'sales_manager',
      positionTitle: 'Менеджер по продажам',
      isActive: true,
      createdAt: now,
      updatedAt: now,
    },
  ],
  userSpecializations: [
    { id: 'uspec-1', userId: 'user-service-engineer-field-1', specializationKey: 'proCoffee', createdAt: now },
    { id: 'uspec-2', userId: 'user-service-engineer-field-1', specializationKey: 'filtration', createdAt: now },
    { id: 'uspec-3', userId: 'user-service-engineer-field-1', specializationKey: 'fieldService', createdAt: now },
    { id: 'uspec-4', userId: 'user-service-engineer-auto-1', specializationKey: 'autoCoffee', createdAt: now },
    { id: 'uspec-5', userId: 'user-service-engineer-universal-1', specializationKey: 'grinder', createdAt: now },
    { id: 'uspec-6', userId: 'user-service-engineer-universal-1', specializationKey: 'electronics', createdAt: now },
  ],
  userBrandSkills: [
    { id: 'ubrand-1', userId: 'user-service-engineer-auto-1', brandKey: 'saeco', createdAt: now },
    { id: 'ubrand-2', userId: 'user-service-engineer-auto-1', brandKey: 'delonghi', createdAt: now },
    { id: 'ubrand-3', userId: 'user-service-engineer-auto-1', brandKey: 'philips', createdAt: now },
    { id: 'ubrand-4', userId: 'user-service-engineer-auto-1', brandKey: 'jura', createdAt: now },
  ],
  userZones: [
    { id: 'uzone-1', userId: 'user-service-engineer-field-1', zoneKey: 'kyiv-right-bank', createdAt: now },
    { id: 'uzone-2', userId: 'user-service-engineer-field-1', zoneKey: 'kyiv-region', createdAt: now },
    { id: 'uzone-3', userId: 'user-service-engineer-universal-1', zoneKey: 'kyiv-center', createdAt: now },
  ],
  clients: [
    {
      id: 'client-1',
      telegramUserId: '123456789',
      companyName: 'Surpresso Partner Coffee',
      contactName: 'Анна',
      phone: '+380731231818',
      isActive: true,
      createdAt: '2026-03-01T09:00:00.000Z',
      updatedAt: '2026-03-01T09:00:00.000Z',
    },
  ],
  equipment: [
    {
      id: 'eq-101',
      clientId: 'client-1',
      type: 'coffee_machine',
      brand: 'La Marzocco',
      model: 'Linea PB',
      serial: 'LM-2234-7781',
      internalNumber: 'SPB-001',
      status: 'active',
      createdAt: '2026-03-24T10:00:00.000Z',
      updatedAt: '2026-03-24T10:00:00.000Z',
    },
    {
      id: 'eq-102',
      clientId: 'client-1',
      type: 'grinder',
      brand: 'Mahlkonig',
      model: 'E65S',
      serial: 'MK-8892-1123',
      internalNumber: 'SPB-002',
      status: 'active',
      createdAt: '2026-03-24T10:10:00.000Z',
      updatedAt: '2026-03-24T10:10:00.000Z',
    },
    {
      id: 'eq-103',
      clientId: 'client-1',
      type: 'water_filter',
      brand: 'BWT',
      model: 'Bestmax Premium',
      serial: 'BWT-9012',
      internalNumber: 'SPB-003',
      status: 'maintenance',
      createdAt: '2026-03-24T10:20:00.000Z',
      updatedAt: '2026-03-24T10:20:00.000Z',
    },
  ],
  serviceRequests: [
    {
      id: 'req-5001',
      type: 'service_repair',
      clientId: 'client-1',
      equipmentId: 'eq-101',
      title: 'Проблема с давлением в группе',
      category: 'coffee_machine',
      description: 'Давление нестабильно во второй группе',
      urgency: 'high',
      canOperateNow: true,
      media: [],
      status: 'in_progress',
      source: 'telegram_miniapp',
      assignedDepartment: 'service',
      assignedToUserId: 'user-service-engineer-field-1',
      createdAt: '2026-03-31T10:15:00.000Z',
      updatedAt: '2026-03-31T11:00:00.000Z',
    },
    {
      id: 'req-5002',
      type: 'coffee_order',
      clientId: 'client-1',
      equipmentId: null,
      title: 'Заказ кофе на следующую неделю',
      category: 'general',
      description: 'Нужна поставка двух сортов под эспрессо и фильтр.',
      urgency: 'normal',
      canOperateNow: true,
      media: [],
      status: 'new',
      source: 'telegram_miniapp',
      assignedDepartment: 'sales',
      assignedToUserId: null,
      createdAt: '2026-04-01T08:20:00.000Z',
      updatedAt: '2026-04-01T08:20:00.000Z',
    },
  ],
  serviceRequestHistory: [
    {
      id: 'srh-1',
      serviceRequestId: 'req-5001',
      previousStatus: 'new',
      nextStatus: 'in_progress',
      changedByUserId: 'user-service-head-1',
      changedByRole: 'service_head',
      comment: 'Взяли в работу после звонка клиенту',
      createdAt: '2026-03-31T11:00:00.000Z',
    },
  ],
  serviceRequestNotes: [
    {
      id: 'srn-1',
      serviceRequestId: 'req-5001',
      authorId: 'user-service-head-1',
      authorRole: 'service_head',
      text: 'Проверить наличие прокладки перед выездом.',
      createdAt: '2026-03-31T11:10:00.000Z',
    },
  ],
};
