import { hashPassword } from '../../domain/security/passwordHasher.js';

const now = new Date().toISOString();

export const seed = {
  users: [
    {
      id: 'user-manager-1',
      email: 'manager@surpresso.local',
      passwordHash: hashPassword('Manager123!'),
      name: 'Manager Demo',
      role: 'manager',
      isActive: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'user-service-1',
      email: 'service@surpresso.local',
      passwordHash: hashPassword('Service123!'),
      name: 'Service Demo',
      role: 'service',
      isActive: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'user-seo-1',
      email: 'seo@surpresso.local',
      passwordHash: hashPassword('Seo123!'),
      name: 'SEO Demo',
      role: 'seo',
      isActive: true,
      createdAt: now,
      updatedAt: now,
    },
  ],
  clients: [
    {
      id: 'client-1',
      telegramUserId: '123456789',
      companyName: 'Surpresso Partner Coffee',
      contactName: 'Анна',
      phone: '+380731231818',
      isActive: true,
      createdAt: '2026-03-01T09:00:00.000Z',
      updatedAt: '2026-03-01T09:00:00.000Z',
    },
  ],
  equipment: [
    {
      id: 'eq-101',
      clientId: 'client-1',
      type: 'coffee_machine',
      brand: 'La Marzocco',
      model: 'Linea PB',
      serial: 'LM-2234-7781',
      internalNumber: 'SPB-001',
      status: 'active',
      createdAt: '2026-03-24T10:00:00.000Z',
      updatedAt: '2026-03-24T10:00:00.000Z',
    },
    {
      id: 'eq-102',
      clientId: 'client-1',
      type: 'grinder',
      brand: 'Mahlkonig',
      model: 'E65S',
      serial: 'MK-8892-1123',
      internalNumber: 'SPB-002',
      status: 'active',
      createdAt: '2026-03-24T10:10:00.000Z',
      updatedAt: '2026-03-24T10:10:00.000Z',
    },
    {
      id: 'eq-103',
      clientId: 'client-1',
      type: 'water_filter',
      brand: 'BWT',
      model: 'Bestmax Premium',
      serial: 'BWT-9012',
      internalNumber: 'SPB-003',
      status: 'maintenance',
      createdAt: '2026-03-24T10:20:00.000Z',
      updatedAt: '2026-03-24T10:20:00.000Z',
    },
  ],
  serviceRequests: [
    {
      id: 'req-5001',
      clientId: 'client-1',
      equipmentId: 'eq-101',
      category: 'coffee_machine',
      description: 'Давление нестабильно во второй группе',
      urgency: 'high',
      canOperateNow: true,
      media: [],
      status: 'in_progress',
      source: 'telegram_miniapp',
      assignedToUserId: null,
      createdAt: '2026-03-31T10:15:00.000Z',
      updatedAt: '2026-03-31T11:00:00.000Z',
    },
    {
      id: 'req-5002',
      clientId: 'client-1',
      equipmentId: 'eq-102',
      category: 'grinder',
      description: 'Появился скрип при помоле',
      urgency: 'medium',
      canOperateNow: true,
      media: [],
      status: 'new',
      source: 'telegram_miniapp',
      assignedToUserId: null,
      createdAt: '2026-04-01T08:20:00.000Z',
      updatedAt: '2026-04-01T08:20:00.000Z',
    },
  ],
};
