import { hashPassword } from '../../domain/security/passwordHasher.js';

const now = new Date().toISOString();

export const seed = {
  users: [
    {
      id: 'user-owner-1',
      email: 'owner@surpresso.local',
      phone: '+10000000001',
      passwordHash: hashPassword('Owner123!'),
      fullName: 'Owner Demo',
      role: 'owner',
      positionTitle: 'Owner',
      isActive: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'user-director-1',
      email: 'director@surpresso.local',
      phone: '+10000000002',
      passwordHash: hashPassword('Director123!'),
      fullName: 'Director Demo',
      role: 'director',
      positionTitle: 'Executive Director',
      isActive: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'user-service-head-1',
      email: 'service.head@surpresso.local',
      phone: '+10000000003',
      passwordHash: hashPassword('ServiceHead123!'),
      fullName: 'Service Head Demo',
      role: 'service_head',
      positionTitle: 'Service Head',
      isActive: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'user-service-engineer-1',
      email: 'service.engineer@surpresso.local',
      phone: '+10000000004',
      passwordHash: hashPassword('Engineer123!'),
      fullName: 'Service Engineer Demo',
      role: 'service_engineer',
      positionTitle: 'Service Engineer (Zone A)',
      isActive: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'user-sales-manager-1',
      email: 'sales.manager@surpresso.local',
      phone: '+10000000005',
      passwordHash: hashPassword('Sales123!'),
      fullName: 'Sales Manager Demo',
      role: 'sales_manager',
      positionTitle: 'Sales Manager',
      isActive: true,
      createdAt: now,
      updatedAt: now,
    },
  ],
  clients: [
    {
      id: 'client-1',
      telegramUserId: '123456789',
      companyName: 'Surpresso Partner Coffee',
      contactName: 'Анна',
      phone: '+380731231818',
      isActive: true,
      createdAt: '2026-03-01T09:00:00.000Z',
      updatedAt: '2026-03-01T09:00:00.000Z',
    },
  ],
  equipment: [
    {
      id: 'eq-101',
      clientId: 'client-1',
      type: 'coffee_machine',
      brand: 'La Marzocco',
      model: 'Linea PB',
      serial: 'LM-2234-7781',
      internalNumber: 'SPB-001',
      status: 'active',
      createdAt: '2026-03-24T10:00:00.000Z',
      updatedAt: '2026-03-24T10:00:00.000Z',
    },
    {
      id: 'eq-102',
      clientId: 'client-1',
      type: 'grinder',
      brand: 'Mahlkonig',
      model: 'E65S',
      serial: 'MK-8892-1123',
      internalNumber: 'SPB-002',
      status: 'active',
      createdAt: '2026-03-24T10:10:00.000Z',
      updatedAt: '2026-03-24T10:10:00.000Z',
    },
  ],
  serviceRequests: [
    {
      id: 'req-5001',
      clientId: 'client-1',
      equipmentId: 'eq-101',
      category: 'service_repair',
      description: 'Давление нестабильно во второй группе',
      urgency: 'high',
      canOperateNow: true,
      media: [],
      status: 'in_progress',
      source: 'telegram_miniapp',
      assignedToUserId: 'user-service-engineer-1',
      createdAt: '2026-03-31T10:15:00.000Z',
      updatedAt: '2026-03-31T11:00:00.000Z',
    },
    {
      id: 'req-5002',
      clientId: 'client-1',
      equipmentId: 'eq-102',
      category: 'coffee_order',
      description: 'Нужна поставка на следующую неделю',
      urgency: 'normal',
      canOperateNow: true,
      media: [],
      status: 'new',
      source: 'telegram_miniapp',
      assignedToUserId: 'user-sales-manager-1',
      createdAt: '2026-04-01T08:20:00.000Z',
      updatedAt: '2026-04-01T08:20:00.000Z',
    },
  ],
  serviceRequestHistory: [
    {
      id: 'srh-1',
      serviceRequestId: 'req-5001',
      previousStatus: 'new',
      nextStatus: 'in_progress',
      changedByUserId: 'user-service-head-1',
      changedByRole: 'service_head',
      comment: 'Назначено инженеру зоны A',
      createdAt: '2026-03-31T11:00:00.000Z',
    },
  ],
  serviceRequestNotes: [
    {
      id: 'srn-1',
      serviceRequestId: 'req-5001',
      authorId: 'user-service-head-1',
      authorRole: 'service_head',
      text: 'Проверить наличие прокладки перед выездом.',
      createdAt: '2026-03-31T11:10:00.000Z',
    },
  ],
};
