ALTER TABLE "User" RENAME COLUMN "name" TO "fullName";
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "phone" TEXT NOT NULL DEFAULT '';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "positionTitle" TEXT NOT NULL DEFAULT '';
